fix

diff --git a/.github/workflows/cleanup-on-create.yaml b/.github/workflows/cleanup-on-create.yaml
--- a/.github/workflows/cleanup-on-create.yaml
+++ b/.github/workflows/cleanup-on-create.yaml
@@ -1,52 +1,62 @@
+# This workflow will run upon repository creation and clean up
+# all files that are not strictly required to build an AEM Live project
+# but that we use to develop the project template. This includes this
+# particular workflow file.
 on:
-  push:
+  create:
     branches:
       - main
   workflow_dispatch:
-
 jobs:
   cleanup:
     runs-on: ubuntu-latest
     permissions:
       contents: write
       actions: write
+    # only run if commit message is "Initial commit" on main branch
+    if: ${{ github.event_name == 'workflow_dispatch' || ( github.ref == 'refs/heads/main' && !(contains(github.event, 'head_commit') || github.event.head_commit.message == 'Initial commit' )) }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
-      - name: Debug GitHub Variables
+      - name: Use Node.js 20
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+      - name: Remove Helper Files
         run: |
-          echo "Event Name: ${{ github.event_name }}"
-          echo "Ref: ${{ github.ref }}"
-          echo "Head Commit: ${{ github.event.head_commit }}"
-          echo "Head Commit Message: ${{ github.event.head_commit.message }}"
+          rm -rf \
+            .github/workflows/cleanup-on-create.yaml \
+            CHANGELOG.md
 
-      # Only run if the commit message is "Initial commit" on main branch
-      - name: Conditional Cleanup
-        if: ${{ github.ref == 'refs/heads/main' && github.event.head_commit.message == 'Initial commit' }}
+      - name: Remove Form Developement Files
         run: |
-          # Remove unnecessary files
-          rm -rf .github/workflows/cleanup-on-create.yaml CHANGELOG.md
-          rm -rf .circleci .npmrc test rollup playwright.config.js
+          rm -rf \
+            .circleci .npmrc test rollup playwright.config.js
 
-          # Update .eslintignore
+      - name: Update .eslintignore
+        run: |
           sed -i '/^rollup/d' .eslintignore
           sed -i '/^helix-importer-ui/d' .eslintignore
 
-          # Update package.json
+      - name: Update Package.json
+        run: |
           rm -rf package.json package-lock.json
           mv package-prod.json package.json
           mv package-prod-lock.json package-lock.json
 
-          # Initialize README
+      - name: Initialize README
+        # replace {repo} and {owner} with the actual values
+        run: |
           sed -i.bak "s/{repo}/$(basename ${{ github.repository }})/g" README.md
           sed -i.bak "s/{owner}/$(dirname ${{ github.repository }})/g" README.md
-
-          # Initialize Pull Request Template
+      - name: Initialize Pull Request Template
+        run: |
           sed -i.bak "s/aem-boilerplate-forms/$(basename ${{ github.repository }})/g" .github/pull_request_template.md
           sed -i.bak "s/adobe-rnd/$(dirname ${{ github.repository }})/g" .github/pull_request_template.md
 
-          # Commit back to the repository
+        # commit back to the repository
+      - name: Commit changes
+        run: |
           git config --local user.email "helix@adobe.com"
           git config --local user.name "AEM Bot"
           git add .
